//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public int PercentageVAT { get; set; }
        public decimal AmountVAT { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int DbStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual DbStatus_lu DbStatus_lu { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
